name: sanad_app
description: "Sanad - Mental Health Support App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.6.2

  # Network & Storage
  dio: ^5.7.0
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.6
  firebase_analytics: ^11.3.6

  # Authentication
  google_sign_in: ^6.2.2

  # UI & UX
  share_plus: ^10.1.3
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.2
  vibration: ^2.0.1
  google_fonts: ^6.2.1
  intl: ^0.20.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
